// picsum.photos/seed/{name}/w/h — returns a consistent image per seed string
function img(seed: string) {
  return `https://picsum.photos/seed/${encodeURIComponent(seed)}/400/400`;
}

export const beautyProducts = [
  // Cleansers
  {
    name: 'CeraVe Hydrating Facial Cleanser',
    brand: 'CeraVe',
    category: 'cleanser',
    price: 18.99,
    description: 'A gentle, non-foaming cleanser that hydrates while cleansing. Contains ceramides and hyaluronic acid. Dermatologist recommended for dry to normal skin.',
    image_url: img('cerave-cleanser'),
    attributes: { skin_type: 'dry', fragrance_free: true, cruelty_free: false },
  },
  {
    name: 'La Roche-Posay Toleriane Hydrating Gentle Cleanser',
    brand: 'La Roche-Posay',
    category: 'cleanser',
    price: 24.95,
    description: 'Ultra-gentle cleanser for sensitive and dry skin. Soap-free, fragrance-free formula that maintains the skin barrier.',
    image_url: img('laroche-toleriane-cleanser'),
    attributes: { skin_type: 'sensitive', fragrance_free: true, cruelty_free: false },
  },
  {
    name: 'Simple Kind to Skin Moisturising Facial Wash',
    brand: 'Simple',
    category: 'cleanser',
    price: 9.99,
    description: 'No artificial perfume or harsh chemicals. Contains triple-purified water and skin-loving ingredients.',
    image_url: img('simple-facial-wash'),
    attributes: { skin_type: 'sensitive', fragrance_free: true, cruelty_free: true },
  },
  {
    name: 'Neutrogena Oil-Free Acne Wash',
    brand: 'Neutrogena',
    category: 'cleanser',
    price: 14.49,
    description: 'Salicylic acid cleanser that fights breakouts while gently cleansing skin. Oil-free formula ideal for acne-prone and oily skin.',
    image_url: img('neutrogena-acne-wash'),
    attributes: { skin_type: 'oily', fragrance_free: false, cruelty_free: false },
  },
  {
    name: 'Cetaphil Gentle Skin Cleanser',
    brand: 'Cetaphil',
    category: 'cleanser',
    price: 16.99,
    description: 'Clinically proven gentle formula suitable for all skin types. Soap-free and non-irritating.',
    image_url: img('cetaphil-gentle-cleanser'),
    attributes: { skin_type: 'all', fragrance_free: true, cruelty_free: false },
  },
  {
    name: 'The Ordinary Squalane Cleanser',
    brand: 'The Ordinary',
    category: 'cleanser',
    price: 12.50,
    description: 'A gentle, balancing cleanser formulated with squalane. Removes makeup and impurities without stripping moisture.',
    image_url: img('ordinary-squalane-cleanser'),
    attributes: { skin_type: 'dry', fragrance_free: true, cruelty_free: true },
  },
  {
    name: "Paula's Choice RESIST Perfectly Balanced Foaming Cleanser",
    brand: "Paula's Choice",
    category: 'cleanser',
    price: 32.00,
    description: 'Lightweight foaming cleanser for normal to oily skin. Removes excess oil and impurities without over-drying.',
    image_url: img('paulas-choice-foaming-cleanser'),
    attributes: { skin_type: 'oily', fragrance_free: true, cruelty_free: true },
  },
  {
    name: 'Bioderma Sensibio H2O Micellar Water',
    brand: 'Bioderma',
    category: 'cleanser',
    price: 22.95,
    description: 'Iconic micellar water that gently removes makeup and cleanses sensitive skin. No rinsing required.',
    image_url: img('bioderma-sensibio-micellar'),
    attributes: { skin_type: 'sensitive', fragrance_free: true, cruelty_free: false },
  },

  // Moisturisers
  {
    name: 'CeraVe Moisturising Cream',
    brand: 'CeraVe',
    category: 'moisturiser',
    price: 22.99,
    description: 'Rich, non-greasy moisturiser with ceramides and MVE technology for 24-hour hydration. Ideal for dry to very dry skin.',
    image_url: img('cerave-moisturising-cream'),
    attributes: { skin_type: 'dry', fragrance_free: true, cruelty_free: false },
  },
  {
    name: 'Neutrogena Hydro Boost Water Gel',
    brand: 'Neutrogena',
    category: 'moisturiser',
    price: 29.99,
    description: 'Lightweight water-gel moisturiser with hyaluronic acid. Oil-free formula that keeps skin hydrated all day.',
    image_url: img('neutrogena-hydro-boost'),
    attributes: { skin_type: 'oily', fragrance_free: false, cruelty_free: false },
  },
  {
    name: 'La Roche-Posay Toleriane Double Repair Face Moisturiser',
    brand: 'La Roche-Posay',
    category: 'moisturiser',
    price: 39.95,
    description: 'Restores the skin barrier and provides 48-hour hydration. Contains ceramides and niacinamide.',
    image_url: img('laroche-toleriane-double-repair'),
    attributes: { skin_type: 'sensitive', fragrance_free: true, cruelty_free: false },
  },
  {
    name: 'Aveeno Calm + Restore Oat Gel Moisturiser',
    brand: 'Aveeno',
    category: 'moisturiser',
    price: 26.99,
    description: 'Lightweight gel moisturiser with prebiotic oat and feverfew. Calms and restores sensitive skin.',
    image_url: img('aveeno-calm-restore-gel'),
    attributes: { skin_type: 'sensitive', fragrance_free: true, cruelty_free: false },
  },
  {
    name: 'The Ordinary Natural Moisturising Factors + HA',
    brand: 'The Ordinary',
    category: 'moisturiser',
    price: 10.90,
    description: 'Affordable daily moisturiser combining amino acids, fatty acids, and hyaluronic acid to maintain skin barrier.',
    image_url: img('ordinary-nmf-ha'),
    attributes: { skin_type: 'all', fragrance_free: true, cruelty_free: true },
  },
  {
    name: "Kiehl's Ultra Facial Cream",
    brand: "Kiehl's",
    category: 'moisturiser',
    price: 52.00,
    description: 'Lightweight yet intensely moisturising formula that absorbs quickly. Provides 24-hour hydration in all climates.',
    image_url: img('kiehls-ultra-facial-cream'),
    attributes: { skin_type: 'all', fragrance_free: false, cruelty_free: false },
  },
  {
    name: 'Tatcha The Water Cream',
    brand: 'Tatcha',
    category: 'moisturiser',
    price: 89.00,
    description: 'Oil-free water cream that controls shine and minimises pores. Contains Japanese wild rose and leopard lily.',
    image_url: img('tatcha-water-cream'),
    attributes: { skin_type: 'oily', fragrance_free: false, cruelty_free: true },
  },

  // SPF
  {
    name: 'La Roche-Posay Anthelios Ultra-Light Fluid SPF 50+',
    brand: 'La Roche-Posay',
    category: 'spf',
    price: 36.95,
    description: 'Ultra-light, fast-absorbing SPF50+ sunscreen. Water-resistant, non-comedogenic. Suitable for sensitive skin.',
    image_url: img('laroche-anthelios-spf50'),
    attributes: { skin_type: 'sensitive', spf_rating: 50, fragrance_free: false, cruelty_free: false },
  },
  {
    name: 'Altruist Dermatologist Sunscreen SPF 50',
    brand: 'Altruist',
    category: 'spf',
    price: 5.99,
    description: 'Dermatologist-developed SPF50 at an affordable price. Lightweight, water-resistant formula.',
    image_url: img('altruist-spf50'),
    attributes: { skin_type: 'all', spf_rating: 50, fragrance_free: false, cruelty_free: true },
  },
  {
    name: 'EltaMD UV Clear Broad-Spectrum SPF 46',
    brand: 'EltaMD',
    category: 'spf',
    price: 49.95,
    description: 'Oil-free, lightweight sunscreen with niacinamide. Ideal for acne-prone and rosacea-prone skin.',
    image_url: img('eltamd-uv-clear-spf46'),
    attributes: { skin_type: 'oily', spf_rating: 46, fragrance_free: true, cruelty_free: true },
  },
  {
    name: 'Neutrogena Ultra Sheer Dry-Touch SPF 50+',
    brand: 'Neutrogena',
    category: 'spf',
    price: 19.99,
    description: 'Ultra-light, non-greasy sunscreen that leaves a matte finish. Broad-spectrum protection.',
    image_url: img('neutrogena-ultra-sheer-spf'),
    attributes: { skin_type: 'oily', spf_rating: 50, fragrance_free: false, cruelty_free: false },
  },
  {
    name: 'Bondi Sands Fragrance Free Daily Moisturiser SPF 50',
    brand: 'Bondi Sands',
    category: 'spf',
    price: 16.99,
    description: 'Australian-made daily moisturiser with SPF50. Fragrance-free, non-greasy formula.',
    image_url: img('bondi-sands-spf50'),
    attributes: { skin_type: 'all', spf_rating: 50, fragrance_free: true, cruelty_free: true },
  },
  {
    name: 'Ultra Violette Queen Screen SPF 50+ Luminising Serum',
    brand: 'Ultra Violette',
    category: 'spf',
    price: 46.00,
    description: 'Luxurious SPF50+ serum-sunscreen hybrid with a luminising finish. Australian-owned, vegan.',
    image_url: img('ultra-violette-queen-screen'),
    attributes: { skin_type: 'dry', spf_rating: 50, fragrance_free: false, cruelty_free: true },
  },
  {
    name: 'Invisible Zinc Tinted Daywear SPF 30',
    brand: 'Invisible Zinc',
    category: 'spf',
    price: 29.95,
    description: 'Mineral sunscreen with a light tint for natural coverage. Zinc oxide formula for sensitive skin.',
    image_url: img('invisible-zinc-tinted-spf30'),
    attributes: { skin_type: 'sensitive', spf_rating: 30, fragrance_free: true, cruelty_free: true },
  },

  // Serums
  {
    name: 'The Ordinary Hyaluronic Acid 2% + B5',
    brand: 'The Ordinary',
    category: 'serum',
    price: 11.90,
    description: 'Hydration support formula with multiple molecular weights of hyaluronic acid. Plumps and hydrates skin.',
    image_url: img('ordinary-hyaluronic-acid-b5'),
    attributes: { skin_type: 'all', fragrance_free: true, cruelty_free: true },
  },
  {
    name: 'The Ordinary Niacinamide 10% + Zinc 1%',
    brand: 'The Ordinary',
    category: 'serum',
    price: 11.90,
    description: 'High-strength vitamin B3 serum that reduces pore appearance and blemishes. Controls sebum production.',
    image_url: img('ordinary-niacinamide-zinc'),
    attributes: { skin_type: 'oily', fragrance_free: true, cruelty_free: true },
  },
  {
    name: 'La Roche-Posay Pure Vitamin C10 Serum',
    brand: 'La Roche-Posay',
    category: 'serum',
    price: 49.95,
    description: '10% pure vitamin C serum for radiance and anti-ageing. Suitable for sensitive skin.',
    image_url: img('laroche-vitamin-c10-serum'),
    attributes: { skin_type: 'sensitive', fragrance_free: true, cruelty_free: false },
  },
  {
    name: "Paula's Choice RESIST 10% Niacinamide Booster",
    brand: "Paula's Choice",
    category: 'serum',
    price: 59.00,
    description: 'Concentrated niacinamide booster that minimises pores and improves skin tone. Fragrance-free.',
    image_url: img('paulas-choice-niacinamide-booster'),
    attributes: { skin_type: 'combination', fragrance_free: true, cruelty_free: true },
  },
  {
    name: 'Drunk Elephant C-Firma Fresh Day Serum',
    brand: 'Drunk Elephant',
    category: 'serum',
    price: 98.00,
    description: 'Potent vitamin C serum with 15% L-ascorbic acid. Brightens, firms, and repairs skin.',
    image_url: img('drunk-elephant-c-firma'),
    attributes: { skin_type: 'all', fragrance_free: false, cruelty_free: true },
  },
  {
    name: 'Estée Lauder Advanced Night Repair Serum',
    brand: 'Estée Lauder',
    category: 'serum',
    price: 115.00,
    description: "Iconic overnight repair serum that targets multiple signs of ageing. Supports skin's natural renewal cycle.",
    image_url: img('estee-lauder-night-repair'),
    attributes: { skin_type: 'all', fragrance_free: false, cruelty_free: false },
  },

  // Toners
  {
    name: "Paula's Choice Skin Perfecting 2% BHA Liquid Exfoliant",
    brand: "Paula's Choice",
    category: 'toner',
    price: 43.00,
    description: 'Cult-favourite BHA exfoliant that unclogs pores and smooths skin. Gentle enough for daily use.',
    image_url: img('paulas-choice-bha-exfoliant'),
    attributes: { skin_type: 'oily', fragrance_free: true, cruelty_free: true },
  },
  {
    name: 'Thayers Witch Hazel Facial Toner',
    brand: 'Thayers',
    category: 'toner',
    price: 16.99,
    description: 'Alcohol-free witch hazel toner with aloe vera. Cleanses and tones without over-drying.',
    image_url: img('thayers-witch-hazel-toner'),
    attributes: { skin_type: 'combination', fragrance_free: false, cruelty_free: true },
  },
  {
    name: 'Pixi Glow Tonic',
    brand: 'Pixi',
    category: 'toner',
    price: 29.00,
    description: '5% glycolic acid toning solution that gently exfoliates and brightens. Leaves skin glowing.',
    image_url: img('pixi-glow-tonic'),
    attributes: { skin_type: 'combination', fragrance_free: false, cruelty_free: true },
  },
  {
    name: 'The Ordinary Glycolic Acid 7% Toning Solution',
    brand: 'The Ordinary',
    category: 'toner',
    price: 14.90,
    description: 'Exfoliating toner with 7% glycolic acid. Smooths skin texture and improves radiance.',
    image_url: img('ordinary-glycolic-acid-toner'),
    attributes: { skin_type: 'combination', fragrance_free: true, cruelty_free: true },
  },
  {
    name: 'La Roche-Posay Effaclar Clarifying Lotion',
    brand: 'La Roche-Posay',
    category: 'toner',
    price: 29.95,
    description: 'Micro-exfoliating toner with glycolic and salicylic acid. Minimises pores and reduces blemishes.',
    image_url: img('laroche-effaclar-lotion'),
    attributes: { skin_type: 'oily', fragrance_free: true, cruelty_free: false },
  },
  {
    name: "Kiehl's Calendula Herbal-Extract Toner",
    brand: "Kiehl's",
    category: 'toner',
    price: 42.00,
    description: 'Alcohol-free toner with calendula flower petals. Calms skin and prepares it for moisturiser.',
    image_url: img('kiehls-calendula-toner'),
    attributes: { skin_type: 'sensitive', fragrance_free: false, cruelty_free: false },
  },

  // Eye creams
  {
    name: 'CeraVe Eye Repair Cream',
    brand: 'CeraVe',
    category: 'eye cream',
    price: 19.99,
    description: 'Fragrance-free eye cream with ceramides and hyaluronic acid. Reduces puffiness and dark circles.',
    image_url: img('cerave-eye-repair-cream'),
    attributes: { skin_type: 'all', fragrance_free: true, cruelty_free: false },
  },
  {
    name: 'Olay Eyes Ultimate Eye Cream',
    brand: 'Olay',
    category: 'eye cream',
    price: 32.99,
    description: 'Multi-action eye cream for dark circles, puffiness, and fine lines. With vitamin B3 and antioxidants.',
    image_url: img('olay-ultimate-eye-cream'),
    attributes: { skin_type: 'all', fragrance_free: false, cruelty_free: false },
  },
  {
    name: "Kiehl's Creamy Eye Treatment with Avocado",
    brand: "Kiehl's",
    category: 'eye cream',
    price: 58.00,
    description: 'Rich, ultra-moisturising eye cream with avocado oil and shea butter. For dry, delicate skin around the eyes.',
    image_url: img('kiehls-avocado-eye-cream'),
    attributes: { skin_type: 'dry', fragrance_free: false, cruelty_free: false },
  },
  {
    name: 'RoC Retinol Correxion Line Smoothing Eye Cream',
    brand: 'RoC',
    category: 'eye cream',
    price: 29.95,
    description: "Anti-ageing eye cream with retinol that visibly smooths fine lines and crow's feet.",
    image_url: img('roc-retinol-eye-cream'),
    attributes: { skin_type: 'all', fragrance_free: false, cruelty_free: false },
  },
  {
    name: 'The Inkey List Caffeine Eye Cream',
    brand: 'The Inkey List',
    category: 'eye cream',
    price: 14.99,
    description: 'Lightweight eye cream with caffeine that reduces puffiness and dark circles. Fast-absorbing formula.',
    image_url: img('inkey-list-caffeine-eye-cream'),
    attributes: { skin_type: 'all', fragrance_free: true, cruelty_free: true },
  },
];
